# Generated by Django 3.2.9 on 2023-07-01 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ing1', models.CharField(max_length=20)),
                ('ing2', models.CharField(max_length=20)),
                ('ing3', models.CharField(max_length=20)),
                ('ing4', models.CharField(max_length=20)),
                ('ing5', models.CharField(max_length=20)),
                ('ing6', models.CharField(max_length=20)),
                ('ing7', models.CharField(max_length=20)),
                ('ing8', models.CharField(max_length=20)),
                ('ing9', models.CharField(max_length=20)),
                ('ing10', models.CharField(max_length=20)),
                ('ing11', models.CharField(max_length=20)),
                ('ing12', models.CharField(max_length=20)),
                ('ing13', models.CharField(max_length=20)),
                ('ing14', models.CharField(max_length=20)),
                ('ing15', models.CharField(max_length=20)),
                ('ing16', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('step1', models.CharField(max_length=20)),
                ('step2', models.CharField(max_length=20)),
                ('step3', models.CharField(max_length=20)),
                ('step4', models.CharField(max_length=20)),
                ('step5', models.CharField(max_length=20)),
                ('step6', models.CharField(max_length=20)),
                ('step7', models.CharField(max_length=20)),
                ('step8', models.CharField(max_length=20)),
                ('step9', models.CharField(max_length=20)),
                ('step10', models.CharField(max_length=20)),
                ('step11', models.CharField(max_length=20)),
                ('step12', models.CharField(max_length=20)),
                ('step13', models.CharField(max_length=20)),
                ('step14', models.CharField(max_length=20)),
                ('step15', models.CharField(max_length=20)),
                ('step16', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='recipes_image')),
                ('sections', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=1000)),
                ('Ingredients', models.CharField(max_length=1000)),
                ('recipesduration', models.CharField(max_length=70)),
                ('Ingredients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingredients', to='accounts.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=70)),
                ('rated_date', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.recipes')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
                ('allergy', models.CharField(max_length=70)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
